# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

title: Edgar Refskegg
description: A&S Projects and Research

plugins: 
- jekyll-remote-theme

remote_theme: daviddarnes/alembic

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: m3chanical # jekyll-seo-tag > Owners twitter username
author: m3chanical # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Edgar # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/m3chanical
    - https://github.com/refskeggbrewing

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "A&S Research and Thoughts" # The post list page content
    feature_text: |
      Welcome to Edgar's A&S!
    feature_image: "/assets/images/sca_camp.jpg"


# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
#      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Edgar Refskegg" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/heraldry.png" # Site logo, also used in jekyll-seo-tag
description: "Edgar Refskegg's A&S Documentation" # Site description and default description, also used in jekyll-seo-tag
url: "https://refskeggbrewing.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/refskeggbrewing"
email: "edgar@refskeggbrewing.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/heraldry.png'
  32: '/assets/logos/heraldry.png'
  96: '/assets/logos/heraldry.png'
  120: '/assets/logos/heraldry.png'
  144: '/assets/logos/heraldry.png'
  180: '/assets/logos/heraldry.png'
  512: '/assets/logos/heraldry.png'
  1024: '/assets/logos/heraldry.png'

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  Brewing: /brewing/
  Enameling: /enameling/
  Other A&S: /misc/
  Documentation: /documents/
  Presence: /presence/
  About: /about/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
 Twitter: https://twitter.com/m3chanical
 GitHub: https://github.com/refskeggbrewing

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
 Twitter: "#0d94e7"
